### PR TITLE
Fix problem with obs date > submitted date

### LINKED ISSUE #584: Observation Submission From App Sets the Starting & Creation Date Incorrectly
image

### PR DESCRIPTION
**Pull request by floatplane**
I tested this fix by manually setting my computer clock to 7 PM MST, which is past midnight in UTC.

without the fix | with the fix
--- | ---
image | image

Fixes #584

### CODE REVIEW

File: components/observations/uploader/uploadObservation.ts [hunk 1]
```diff
@@ -8,12 +8,17 @@ import {apiDateString} from 'utils/date';
...
+  // local timezone, we mitigate this problem.
+  const adjustedDate = new Date(formData.start_date);
+  adjustedDate.setHours(12, 0, 0, 0);
   const payload: Partial<Observation> = {
     ...formData,
     ...params,
     obs_source: 'public',
     // Date has to be a plain-old YYYY-MM-DD string
-    start_date: apiDateString(formData.start_date),
+    start_date: apiDateString(adjustedDate),
```
Comment (stevekuznetsov) [inline components/observations/uploader/uploadObservation.ts:21]: Could we simply do the formatting without converting to UTC? Might be simpler and in case we ever get observations from the Middle East, would still work ;)

Comment (floatplane) [reply components/observations/uploader/uploadObservation.ts:21]: yes, that's cleaner - I like it

**Comment by floatplane** [comment]
ptal @stevekuznetsov
